version: '3'

services:
  server:
    build:
      context: .
    container_name: restaurant-webserver
    ports:
      - 4406:80
    restart: always
    volumes:
      - ./www:/var/www/html
    env_file:
      - ./docker.env
    networks:
      - becode

  database:
    image: mariadb:10.4.2
    container_name: restaurant-database
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
      - restaurant_data:/var/lib/mysql
    env_file:
      - ./docker.env
    networks:
      - becode

networks:
  becode:

volumes:
  restaurant_data:
